<?php

namespace App\Exports;

use App\Models\Location;
use App\Models\NearMiss;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class nearMissExport implements FromCollection,WithHeadings,WithMapping
{
    /**
    * @return \Illuminate\Support\Collection
    */
    protected $startDate;
    protected $endDate;
    protected $location_id;

    public function __construct($location_id,$startDate,$endDate){
        $this->location_id = $location_id;
        $this->startDate = $startDate;
        $this->endDate = $endDate;
    }
    public function collection()
    {
        $query = NearMiss::where('location_id', $this->location_id);

        if (isset($this->startDate)) {
            $query->where('created_at', '>=', $this->startDate);
        }

        if (isset($this->endDate)) {
            $query->where('created_at', '<=', $this->endDate);
        }
        return $query->get();
    }

    public function headings(): array
    {
        return [
        'location id',
        'time',
        'date',
        'error by',
        'error by other',
        'error detected by',
        'error detected by other',
        'point of detection',
        'error prescription',
        'error labelling',
        'error picking',
        'error placing into basket',
        'error bagging',
        'error preparing dosette tray',
        'error handing out',
        'prescription missing signature',
        'prescription missing signature cause legal checks not done',
        'prescription missing signature cause not trained',
        'prescription missing signature cause person in training',
        'prescription missing signature cause other',
        'prescription missing signature cause other field',
        'prescription expired',
        'prescription expired involve drug',
        'prescription expired drug name',
        'prescription expired cause date not checked',
        'prescription expired cause legal checks not done',
        'prescription expired sop not understood',
        'prescription expired cause other',
        'prescription expired cause other field',
        'prescription old treatment',
        'prescription old treatment cause hospital discharge not actioned',
        'prescription old treatment cause error by prescriber',
        'prescription old treatment cause change not communicated',
        'prescription old treatment cause other',
        'prescription old treatment cause other field',
        'prescription tampered',
        'prescription tampered cause legal checks not done',
        'prescription tampered cause other',
        'prescription tampered cause other field',
        'labelling wrong brand',
        'labelling wrong brand drug prescribed',
        'labelling wrong brand drug labelled',
        'labelling wrong brand cause similar items',
        'labelling wrong brand cause repeated pmr history',
        'labelling wrong brand cause misread prescription',
        'labelling wrong brand cause unclear handwritten prescription',
        'labelling wrong brand cause did not recheck',
        'labelling wrong brand cause other',
        'labelling wrong brand cause other field',
        'labelling wrong direction',
        'labelling wrong direction cause unclear directions',
        'labelling wrong direction cause unclear handwritten prescription',
        'labelling wrong direction cause use of abbreviation',
        'labelling wrong direction cause abbreviation not changed',
        'labelling wrong direction cause repeated pmr history',
        'labelling wrong direction cause did not recheck',
        'labelling wrong direction cause other',
        'labelling wrong direction cause other field',
        'labelling wrong item',
        'labelling wrong item drug prescribed',
        'labelling wrong item drug labelled',
        'labelling wrong item cause similar items',
        'labelling wrong item cause misread prescription',
        'labelling wrong item cause repeated pmr history',
        'labelling wrong item cause unclear handwritten prescription',
        'labelling wrong item cause did not recheck',
        'labelling wrong item cause other',
        'labelling wrong item cause other field',
        'labelling wrong formulation',
        'labelling wrong formulation drug prescribed',
        'labelling wrong formulation drug labelled',
        'labelling wrong formulation cause similar items',
        'labelling wrong formulation cause misread prescription',
        'labelling wrong formulation cause repeated pmr history',
        'labelling wrong formulation cause unclear written prescription',
        'labelling wrong formulation cause did not recheck',
        'labelling wrong formulation cause other',
        'labelling wrong formulation cause other field',
        'labelling wrong patient',
        'labelling wrong patient cause similar patient name',
        'labelling wrong patient cause misread prescription',
        'labelling wrong patient cause unclear handwritten prescription',
        'labelling wrong patient cause did not recheck',
        'labelling wrong patient cause other',
        'labelling wrong patient cause other field',
        'labelling wrong quantity',
        'labelling wrong quantity cause unfamiliar with item',
        'labelling wrong quantity cause calculation error',
        'labelling wrong quantity cause misread prescription',
        'labelling wrong quantity cause use of abbreviation',
        'labelling wrong quantity cause unclear handwritten prescription',
        'labelling wrong quantity cause did not recheck',
        'labelling wrong quantity cause other',
        'labelling wrong quantity cause other field',
        'labelling wrong strength',
        'labelling wrong strength drug prescribed',
        'labelling wrong strength drug labelled',
        'labelling wrong strength cause misread prescription',
        'labelling wrong strength cause repeated pmr history',
        'labelling wrong strength cause unfamiliar with item',
        'labelling wrong strength cause did not recheck',
        'labelling wrong strength cause other',
        'labelling wrong strength cause other field',
        'picking out of date item',
        'picking out of date item drug name',
        'picking out of date item cause did not recheck',
        'picking out of date item cause date not checked',
        'picking out of date item cause items wrong place',
        'picking out of date item cause other',
        'picking out of date item cause other field',
        'picking wrong brand',
        'picking wrong brand drug prescribed',
        'picking wrong brand drug labelled',
        'picking wrong brand cause similar name items',
        'picking wrong brand cause similar packaging',
        'picking wrong brand cause change in packaging',
        'picking wrong brand cause item wrong place',
        'picking wrong brand cause unclear handwritten prescription',
        'picking wrong brand cause misread prescription',
        'picking wrong brand cause imported pi pack',
        'picking wrong brand cause dispensed from picking label',
        'picking wrong brand cause sop not understood',
        'picking wrong brand cause unfamiliar with item',
        'picking wrong brand cause did not recheck',
        'picking wrong brand cause other',
        'picking wrong brand cause other field',
        'picking wrong item',
        'picking wrong item drug prescribed',
        'picking wrong item drug labelled',
        'picking wrong item cause similar name items',
        'picking wrong item cause similar packaging',
        'picking wrong item cause change in packaging',
        'picking wrong item cause unclear handwritten prescription',
        'picking wrong item cause misread prescription',
        'picking wrong item cause imported pi pack',
        'picking wrong item cause dispensed from picking label',
        'picking wrong item cause unfamiliar with item',
        'picking wrong item cause did not recheck',
        'picking wrong item cause other',
        'picking wrong item cause other field',
        'picking wrong quantity',
        'picking wrong quantity cause counting mistake',
        'picking wrong quantity cause calculation error',
        'picking wrong quantity cause similar packaging',
        'picking wrong quantity cause change in packaging',
        'picking wrong quantity cause did not recheck',
        'picking wrong quantity cause other',
        'picking wrong quantity cause other field',
        'picking wrong strength',
        'picking wrong strength drug prescribed',
        'picking wrong strength drug labelled',
        'picking wrong strength cause similar name items',
        'picking wrong strength cause similar packaging',
        'picking wrong strength cause change in packaging',
        'picking wrong strength cause unclear handwritten prescription',
        'picking wrong strength cause misread prescription',
        'picking wrong strength cause imported pi pack',
        'picking wrong strength cause dispensed from picking label',
        'picking wrong strength cause unfamiliar with item',
        'picking wrong strength cause did not recheck',
        'picking wrong strength cause other',
        'picking wrong strength cause other field',
        'picking wrong formulation',
        'picking wrong formulation drug prescribed',
        'picking wrong formulation drug labelled',
        'picking wrong formulation cause similar name items',
        'picking wrong formulation cause similar packaging',
        'picking wrong formulation cause change in packaging',
        'picking wrong formulation cause unclear handwritten prescription',
        'picking wrong formulation cause misread prescription',
        'picking wrong formulation cause imported pi pack',
        'picking wrong formulation cause dispensed from picking label',
        'picking wrong formulation cause unfamiliar with item',
        'picking wrong formulation cause did not recheck',
        'picking wrong formulation cause other',
        'picking wrong formulation cause other field',
    'placing basket another patient label basket',
    'placing basket another patient cause weak adhesive labels',
    'placing basket another patient cause area cluttered baskets',
    'placing basket another patient cause basket was moved',
    'placing basket another patient cause labels stuck basket',
    'placing basket another patient cause other',
    'placing basket another patient cause other field',
    'placing basket wrong basket',
    'placing basket wrong basket cause area cluttered baskets',
    'placing basket wrong basket cause basket was moved',
    'placing basket wrong basket cause other',
    'placing basket wrong basket cause other field',
    'placing basket missing item',
    'placing basket missing item cause missing cd sticket',
    'placing basket missing item cause label lost',
    'placing basket missing item cause distracted item left out',
    'placing basket missing item cause other',
    'placing basket missing item cause other field',
    'placing basket label wrong item',
    'placing basket wrong item cause weak adhesive labels',
    'placing basket wrong item cause similar name items',
    'placing basket wrong item cause similar packaging',
    'placing basket wrong item cause change in packaging',
    'placing basket wrong item cause did not recheck',
    'placing basket wrong item cause other',
    'placing basket wrong item cause other field',
    'bagging wrong bag label',
    'bagging wrong bag label cause similar patient name',
    'bagging wrong bag label cause label reprinted',
    'bagging wrong bag label cause cluttered bagging area',
    'bagging wrong bag label cause other',
    'bagging wrong bag label cause other field',
    'bagging another patient med in bag',
    'bagging another patient med in bag cause similar patient name',
    'bagging another patient med in bag cause cluttered bagging area',
    'bagging another patient med in bag cause bag different patient',
    'bagging another patient med in bag cause other',
    'bagging another patient med in bag cause other field',
    'bagging missed items',
    'bagging missed items cause cluttered bagging area',
    'bagging missed items cause distracted item left out',
    'bagging missed items cause missing cd sticker',
    'bagging missed items cause other',
    'bagging missed items cause other field',
    'preparing dosette tray wrong day time',
    'preparing dosette tray error patient mar chart',
    'preparing dosette tray extra quantity on tray',
    'preparing dosette tray error in description',
    'preparing dosette tray wrong bag label',
    'preparing dosette tray external item missing',
    'preparing dosette tray tray item missing',
    'preparing dosette tray error on blister pack',
    'preparing dosette tray blistring cause discharge not actioned',
    'preparing dosette tray blistring cause change not communicated',
    'preparing dosette tray blistring cause other',
    'preparing dosette tray blistring cause other field',
    'handing out to wrong patient',
    'handing out to wrong patient cause similar patient name',
    'handing out to wrong patient cause didnot confirm address',
    'handing out to wrong patient cause other',
    'handing out to wrong patient cause other field',
    'contributing factor staff fewer staff',
    'contributing factor staff not usual pharmacist',
    'contributing factor staff not usual dispense',
    'contributing factor staff pharmacist self checking',
    'contributing factor person dyslexia',
    'contributing factor person dyscalculia',
    'contributing factor envirnoment messy',
    'contributing factor training person in training',
    'contributing factor training person not trained',
    'contributing factor task and workload high number patients',
    'contributing factor task and workload busy otc trade',
    'contributing factor task and workload backlog work',
    'contributing factor task and workload quieter than usual',
    'contributing factor task and workload telephone interruption',
    'contributing factor other',
    'contributing factor other field',
    'created_at',
    'what_was_error',
    'delete_reason',
    'deleted_by',
    'deleted_timestamp',
    'dispensed_at_hub',
    'error'
    
    ];
    }

    public function map($near_miss): array
    {
        return [
            Location::find($near_miss->location_id)->name(),
            $near_miss->time,
            $near_miss->date,
            $near_miss->error_by,
            $near_miss->error_by_other,
            $near_miss->error_detected_by,
            $near_miss->error_detected_by_other,
            $near_miss->point_of_detection,
            ($near_miss->error_prescription ? ($near_miss->error_prescription == 1 ? 'yes' : 'no') : $near_miss->error_prescription),
            ($near_miss->error_labelling ? ($near_miss->error_labelling == 1 ? 'yes' : 'no') : $near_miss->error_labelling),
            ($near_miss->error_picking ? ($near_miss->error_picking == 1 ? 'yes' : 'no') : $near_miss->error_picking),
            ($near_miss->error_placing_into_basket ? ($near_miss->error_placing_into_basket == 1 ? 'yes' : 'no') : $near_miss->error_placing_into_basket),
            ($near_miss->error_bagging ? ($near_miss->error_bagging == 1 ? 'yes' : 'no') : $near_miss->error_bagging),
            ($near_miss->error_preparing_dosette_tray ? ($near_miss->error_preparing_dosette_tray == 1 ? 'yes' : 'no') : $near_miss->error_preparing_dosette_tray),
            ($near_miss->error_handing_out ? ($near_miss->error_handing_out == 1 ? 'yes' : 'no') : $near_miss->error_handing_out),
            ($near_miss->prescription_missing_signature ? ($near_miss->prescription_missing_signature == 1 ? 'yes' : 'no') : $near_miss->prescription_missing_signature),
            ($near_miss->prescription_missing_signature_cause_legal_checks_not_done ? ($near_miss->prescription_missing_signature_cause_legal_checks_not_done == 1 ? 'yes' : 'no') : $near_miss->prescription_missing_signature_cause_legal_checks_not_done),
            ($near_miss->prescription_missing_signature_cause_not_trained ? ($near_miss->prescription_missing_signature_cause_not_trained == 1 ? 'yes' : 'no') : $near_miss->prescription_missing_signature_cause_not_trained),
            ($near_miss->prescription_missing_signature_cause_person_in_training ? ($near_miss->prescription_missing_signature_cause_person_in_training == 1 ? 'yes' : 'no') : $near_miss->prescription_missing_signature_cause_person_in_training),
            ($near_miss->prescription_missing_signature_cause_other ? ($near_miss->prescription_missing_signature_cause_other == 1 ? 'yes' : 'no') : $near_miss->prescription_missing_signature_cause_other),
            ($near_miss->prescription_missing_signature_cause_other_field ? ($near_miss->prescription_missing_signature_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->prescription_missing_signature_cause_other_field),
            ($near_miss->prescription_expired ? ($near_miss->prescription_expired == 1 ? 'yes' : 'no') : $near_miss->prescription_expired),
            ($near_miss->prescription_expired_involve_drug ? ($near_miss->prescription_expired_involve_drug == 1 ? 'yes' : 'no') : $near_miss->prescription_expired_involve_drug),
            ($near_miss->prescription_expired_drug_name ? ($near_miss->prescription_expired_drug_name == 1 ? 'yes' : 'no') : $near_miss->prescription_expired_drug_name),
            ($near_miss->prescription_expired_cause_date_not_checked ? ($near_miss->prescription_expired_cause_date_not_checked == 1 ? 'yes' : 'no') : $near_miss->prescription_expired_cause_date_not_checked),
            ($near_miss->prescription_expired_cause_legal_checks_not_done ? ($near_miss->prescription_expired_cause_legal_checks_not_done == 1 ? 'yes' : 'no') : $near_miss->prescription_expired_cause_legal_checks_not_done),
            ($near_miss->prescription_expired_cause_sop_not_understood ? ($near_miss->prescription_expired_cause_sop_not_understood == 1 ? 'yes' : 'no') : $near_miss->prescription_expired_cause_sop_not_understood),
            ($near_miss->prescription_expired_cause_other ? ($near_miss->prescription_expired_cause_other == 1 ? 'yes' : 'no') : $near_miss->prescription_expired_cause_other),
            $near_miss->prescription_expired_cause_other_field,
            ($near_miss->prescription_old_treatment ? ($near_miss->prescription_old_treatment == 1 ? 'yes' : 'no') : $near_miss->prescription_old_treatment),
            ($near_miss->prescription_old_treatment_cause_hospital_discharge_not_actioned ? ($near_miss->prescription_old_treatment_cause_hospital_discharge_not_actioned == 1 ? 'yes' : 'no') : $near_miss->prescription_old_treatment_cause_hospital_discharge_not_actioned),
            ($near_miss->prescription_old_treatment_cause_error_by_prescriber ? ($near_miss->prescription_old_treatment_cause_error_by_prescriber == 1 ? 'yes' : 'no') : $near_miss->prescription_old_treatment_cause_error_by_prescriber),
            ($near_miss->prescription_old_treatment_cause_change_not_communicated ? ($near_miss->prescription_old_treatment_cause_change_not_communicated == 1 ? 'yes' : 'no') : $near_miss->prescription_old_treatment_cause_change_not_communicated),
            ($near_miss->prescription_old_treatment_cause_other ? ($near_miss->prescription_old_treatment_cause_other == 1 ? 'yes' : 'no') : $near_miss->prescription_old_treatment_cause_other),
            $near_miss->prescription_old_treatment_cause_other_field,
            ($near_miss->prescription_tampered ? ($near_miss->prescription_tampered == 1 ? 'yes' : 'no') : $near_miss->prescription_tampered),
            ($near_miss->prescription_tampered_cause_legal_checks_not_done ? ($near_miss->prescription_tampered_cause_legal_checks_not_done == 1 ? 'yes' : 'no') : $near_miss->prescription_tampered_cause_legal_checks_not_done),
            ($near_miss->prescription_tampered_cause_other ? ($near_miss->prescription_tampered_cause_other == 1 ? 'yes' : 'no') : $near_miss->prescription_tampered_cause_other),
            $near_miss->prescription_tampered_cause_other_field,
            ($near_miss->labelling_wrong_brand ? ($near_miss->labelling_wrong_brand == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand),
            ($near_miss->labelling_wrong_brand_drug_prescribed ? ($near_miss->labelling_wrong_brand_drug_prescribed == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand_drug_prescribed),
            ($near_miss->labelling_wrong_brand_drug_labelled ? ($near_miss->labelling_wrong_brand_drug_labelled == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand_drug_labelled),
            ($near_miss->labelling_wrong_brand_cause_similar_items ? ($near_miss->labelling_wrong_brand_cause_similar_items == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand_cause_similar_items),
            ($near_miss->labelling_wrong_brand_cause_repeated_pmr_history ? ($near_miss->labelling_wrong_brand_cause_repeated_pmr_history == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand_cause_repeated_pmr_history),
            ($near_miss->labelling_wrong_brand_cause_misread_prescription ? ($near_miss->labelling_wrong_brand_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand_cause_misread_prescription),
            ($near_miss->labelling_wrong_brand_cause_unclear_handwritten_prescription ? ($near_miss->labelling_wrong_brand_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand_cause_unclear_handwritten_prescription),
            ($near_miss->labelling_wrong_brand_cause_did_not_recheck ? ($near_miss->labelling_wrong_brand_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand_cause_did_not_recheck),
            ($near_miss->labelling_wrong_brand_cause_other ? ($near_miss->labelling_wrong_brand_cause_other == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand_cause_other),
            ($near_miss->labelling_wrong_brand_cause_other_field ? ($near_miss->labelling_wrong_brand_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_brand_cause_other_field),
            ($near_miss->labelling_wrong_direction ? ($near_miss->labelling_wrong_direction == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_direction),
            ($near_miss->labelling_wrong_direction_cause_unclear_directions ? ($near_miss->labelling_wrong_direction_cause_unclear_directions == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_direction_cause_unclear_directions),
            ($near_miss->labelling_wrong_direction_cause_unclear_handwritten_prescription ? ($near_miss->labelling_wrong_direction_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_direction_cause_unclear_handwritten_prescription),
            ($near_miss->labelling_wrong_direction_cause_use_of_abbreviation ? ($near_miss->labelling_wrong_direction_cause_use_of_abbreviation == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_direction_cause_use_of_abbreviation),
            ($near_miss->labelling_wrong_direction_cause_abbreviation_not_changed ? ($near_miss->labelling_wrong_direction_cause_abbreviation_not_changed == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_direction_cause_abbreviation_not_changed),
            ($near_miss->labelling_wrong_direction_cause_repeated_pmr_history ? ($near_miss->labelling_wrong_direction_cause_repeated_pmr_history == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_direction_cause_repeated_pmr_history),
            ($near_miss->labelling_wrong_direction_cause_did_not_recheck ? ($near_miss->labelling_wrong_direction_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_direction_cause_did_not_recheck),
            ($near_miss->labelling_wrong_direction_cause_other ? ($near_miss->labelling_wrong_direction_cause_other == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_direction_cause_other),
            ($near_miss->labelling_wrong_direction_cause_other_field ? ($near_miss->labelling_wrong_direction_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_direction_cause_other_field),
            ($near_miss->labelling_wrong_item ? ($near_miss->labelling_wrong_item == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item),
            ($near_miss->labelling_wrong_item_drug_prescribed ? ($near_miss->labelling_wrong_item_drug_prescribed == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item_drug_prescribed),
            ($near_miss->labelling_wrong_item_drug_labelled ? ($near_miss->labelling_wrong_item_drug_labelled == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item_drug_labelled),
            ($near_miss->labelling_wrong_item_cause_similar_items ? ($near_miss->labelling_wrong_item_cause_similar_items == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item_cause_similar_items),
            ($near_miss->labelling_wrong_item_cause_misread_prescription ? ($near_miss->labelling_wrong_item_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item_cause_misread_prescription),
            ($near_miss->labelling_wrong_item_cause_repeated_pmr_history ? ($near_miss->labelling_wrong_item_cause_repeated_pmr_history == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item_cause_repeated_pmr_history),
            ($near_miss->labelling_wrong_item_cause_unclear_handwritten_prescription ? ($near_miss->labelling_wrong_item_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item_cause_unclear_handwritten_prescription),
            ($near_miss->labelling_wrong_item_cause_did_not_recheck ? ($near_miss->labelling_wrong_item_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item_cause_did_not_recheck),
            ($near_miss->labelling_wrong_item_cause_other ? ($near_miss->labelling_wrong_item_cause_other == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item_cause_other),
            ($near_miss->labelling_wrong_item_cause_other_field ? ($near_miss->labelling_wrong_item_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_item_cause_other_field),
            ($near_miss->labelling_wrong_formulation ? ($near_miss->labelling_wrong_formulation == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation),
            ($near_miss->labelling_wrong_formulation_drug_prescribed ? ($near_miss->labelling_wrong_formulation_drug_prescribed == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation_drug_prescribed),
            ($near_miss->labelling_wrong_formulation_drug_labelled ? ($near_miss->labelling_wrong_formulation_drug_labelled == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation_drug_labelled),
            ($near_miss->labelling_wrong_formulation_cause_similar_items ? ($near_miss->labelling_wrong_formulation_cause_similar_items == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation_cause_similar_items),
            ($near_miss->labelling_wrong_formulation_cause_misread_prescription ? ($near_miss->labelling_wrong_formulation_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation_cause_misread_prescription),
            ($near_miss->labelling_wrong_formulation_cause_repeated_pmr_history ? ($near_miss->labelling_wrong_formulation_cause_repeated_pmr_history == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation_cause_repeated_pmr_history),
            ($near_miss->labelling_wrong_formulation_cause_unclear_written_prescription ? ($near_miss->labelling_wrong_formulation_cause_unclear_written_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation_cause_unclear_written_prescription),
            ($near_miss->labelling_wrong_formulation_cause_did_not_recheck ? ($near_miss->labelling_wrong_formulation_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation_cause_did_not_recheck),
            ($near_miss->labelling_wrong_formulation_cause_other ? ($near_miss->labelling_wrong_formulation_cause_other == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation_cause_other),
            ($near_miss->labelling_wrong_formulation_cause_other_field ? ($near_miss->labelling_wrong_formulation_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_formulation_cause_other_field),
            ($near_miss->labelling_wrong_patient ? ($near_miss->labelling_wrong_patient == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_patient),
            ($near_miss->labelling_wrong_patient_cause_similar_patient_name ? ($near_miss->labelling_wrong_patient_cause_similar_patient_name == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_patient_cause_similar_patient_name),
            ($near_miss->labelling_wrong_patient_cause_misread_prescription ? ($near_miss->labelling_wrong_patient_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_patient_cause_misread_prescription),
            ($near_miss->labelling_wrong_patient_cause_unclear_handwritten_prescription ? ($near_miss->labelling_wrong_patient_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_patient_cause_unclear_handwritten_prescription),
            ($near_miss->labelling_wrong_patient_cause_did_not_recheck ? ($near_miss->labelling_wrong_patient_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_patient_cause_did_not_recheck),
            ($near_miss->labelling_wrong_patient_cause_other ? ($near_miss->labelling_wrong_patient_cause_other == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_patient_cause_other),
            ($near_miss->labelling_wrong_patient_cause_other_field ? ($near_miss->labelling_wrong_patient_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_patient_cause_other_field),
            ($near_miss->labelling_wrong_quantity ? ($near_miss->labelling_wrong_quantity == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_quantity),
            ($near_miss->labelling_wrong_quantity_cause_unfamiliar_with_item ? ($near_miss->labelling_wrong_quantity_cause_unfamiliar_with_item == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_quantity_cause_unfamiliar_with_item),
            ($near_miss->labelling_wrong_quantity_cause_calculation_error ? ($near_miss->labelling_wrong_quantity_cause_calculation_error == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_quantity_cause_calculation_error),
            ($near_miss->labelling_wrong_quantity_cause_misread_prescription ? ($near_miss->labelling_wrong_quantity_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_quantity_cause_misread_prescription),
            ($near_miss->labelling_wrong_quantity_cause_use_of_abbreviation ? ($near_miss->labelling_wrong_quantity_cause_use_of_abbreviation == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_quantity_cause_use_of_abbreviation),
            ($near_miss->labelling_wrong_quantity_cause_unclear_handwritten_prescription ? ($near_miss->labelling_wrong_quantity_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_quantity_cause_unclear_handwritten_prescription),
            ($near_miss->labelling_wrong_quantity_cause_did_not_recheck ? ($near_miss->labelling_wrong_quantity_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_quantity_cause_did_not_recheck),
            ($near_miss->labelling_wrong_quantity_cause_other ? ($near_miss->labelling_wrong_quantity_cause_other == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_quantity_cause_other),
            ($near_miss->labelling_wrong_quantity_cause_other_field ? ($near_miss->labelling_wrong_quantity_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_quantity_cause_other_field),
            ($near_miss->labelling_wrong_strength ? ($near_miss->labelling_wrong_strength == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_strength),
            ($near_miss->labelling_wrong_strength_drug_prescribed ? ($near_miss->labelling_wrong_strength_drug_prescribed == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_strength_drug_prescribed),
            ($near_miss->labelling_wrong_strength_drug_labelled ? ($near_miss->labelling_wrong_strength_drug_labelled == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_strength_drug_labelled),
            ($near_miss->labelling_wrong_strength_cause_misread_prescription ? ($near_miss->labelling_wrong_strength_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_strength_cause_misread_prescription),
            ($near_miss->labelling_wrong_strength_cause_repeated_pmr_history ? ($near_miss->labelling_wrong_strength_cause_repeated_pmr_history == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_strength_cause_repeated_pmr_history),
            ($near_miss->labelling_wrong_strength_cause_unclear_handwritten_prescription ? ($near_miss->labelling_wrong_strength_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_strength_cause_unclear_handwritten_prescription),
            ($near_miss->labelling_wrong_strength_cause_did_not_recheck ? ($near_miss->labelling_wrong_strength_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_strength_cause_did_not_recheck),
            ($near_miss->labelling_wrong_strength_cause_other ? ($near_miss->labelling_wrong_strength_cause_other == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_strength_cause_other),
            ($near_miss->labelling_wrong_strength_cause_other_field ? ($near_miss->labelling_wrong_strength_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->labelling_wrong_strength_cause_other_field),
            ($near_miss->picking_out_of_date_item ? ($near_miss->picking_out_of_date_item == 1 ? 'yes' : 'no') : $near_miss->picking_out_of_date_item),
            ($near_miss->picking_out_of_date_item_drug_name ? ($near_miss->picking_out_of_date_item_drug_name == 1 ? 'yes' : 'no') : $near_miss->picking_out_of_date_item_drug_name),
            ($near_miss->picking_out_of_date_item_cause_did_not_recheck ? ($near_miss->picking_out_of_date_item_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->picking_out_of_date_item_cause_did_not_recheck),
            ($near_miss->picking_out_of_date_item_cause_date_not_checked ? ($near_miss->picking_out_of_date_item_cause_date_not_checked == 1 ? 'yes' : 'no') : $near_miss->picking_out_of_date_item_cause_date_not_checked),
            ($near_miss->picking_out_of_date_item_cause_items_wrong_place ? ($near_miss->picking_out_of_date_item_cause_items_wrong_place == 1 ? 'yes' : 'no') : $near_miss->picking_out_of_date_item_cause_items_wrong_place),
            ($near_miss->picking_out_of_date_item_cause_other ? ($near_miss->picking_out_of_date_item_cause_other == 1 ? 'yes' : 'no') : $near_miss->picking_out_of_date_item_cause_other),
            ($near_miss->picking_out_of_date_item_cause_other_field ? ($near_miss->picking_out_of_date_item_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->picking_out_of_date_item_cause_other_field),
            ($near_miss->picking_wrong_brand ? ($near_miss->picking_wrong_brand == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand),
            ($near_miss->picking_wrong_brand_drug_prescribed ? ($near_miss->picking_wrong_brand_drug_prescribed == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_drug_prescribed),
            ($near_miss->picking_wrong_brand_drug_labelled ? ($near_miss->picking_wrong_brand_drug_labelled == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_drug_labelled),
            ($near_miss->picking_wrong_brand_cause_similar_name_items ? ($near_miss->picking_wrong_brand_cause_similar_name_items == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_similar_name_items),
            ($near_miss->picking_wrong_brand_cause_similar_packaging ? ($near_miss->picking_wrong_brand_cause_similar_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_similar_packaging),
            ($near_miss->picking_wrong_brand_cause_change_in_packaging ? ($near_miss->picking_wrong_brand_cause_change_in_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_change_in_packaging),
            ($near_miss->picking_wrong_brand_cause_item_wrong_place ? ($near_miss->picking_wrong_brand_cause_item_wrong_place == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_item_wrong_place),
            ($near_miss->picking_wrong_brand_cause_unclear_handwritten_prescription ? ($near_miss->picking_wrong_brand_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_unclear_handwritten_prescription),
            ($near_miss->picking_wrong_brand_cause_misread_prescription ? ($near_miss->picking_wrong_brand_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_misread_prescription),
            ($near_miss->picking_wrong_brand_cause_imported_pi_pack ? ($near_miss->picking_wrong_brand_cause_imported_pi_pack == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_imported_pi_pack),
            ($near_miss->picking_wrong_brand_cause_dispensed_from_picking_label ? ($near_miss->picking_wrong_brand_cause_dispensed_from_picking_label == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_dispensed_from_picking_label),
            ($near_miss->picking_wrong_brand_cause_sop_not_understood ? ($near_miss->picking_wrong_brand_cause_sop_not_understood == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_sop_not_understood),
            ($near_miss->picking_wrong_brand_cause_unfamiliar_with_item ? ($near_miss->picking_wrong_brand_cause_unfamiliar_with_item == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_unfamiliar_with_item),
            ($near_miss->picking_wrong_brand_cause_did_not_recheck ? ($near_miss->picking_wrong_brand_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_did_not_recheck),
            ($near_miss->picking_wrong_brand_cause_other ? ($near_miss->picking_wrong_brand_cause_other == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_other),
            ($near_miss->picking_wrong_brand_cause_other_field ? ($near_miss->picking_wrong_brand_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_brand_cause_other_field),
            ($near_miss->picking_wrong_item ? ($near_miss->picking_wrong_item == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item),
            ($near_miss->picking_wrong_item_drug_prescribed ? ($near_miss->picking_wrong_item_drug_prescribed == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_drug_prescribed),
            ($near_miss->picking_wrong_item_drug_labelled ? ($near_miss->picking_wrong_item_drug_labelled == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_drug_labelled),
            ($near_miss->picking_wrong_item_cause_similar_name_items ? ($near_miss->picking_wrong_item_cause_similar_name_items == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_similar_name_items),
            ($near_miss->picking_wrong_item_cause_similar_packaging ? ($near_miss->picking_wrong_item_cause_similar_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_similar_packaging),
            ($near_miss->picking_wrong_item_cause_change_in_packaging ? ($near_miss->picking_wrong_item_cause_change_in_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_change_in_packaging),
            ($near_miss->picking_wrong_item_cause_unclear_handwritten_prescription ? ($near_miss->picking_wrong_item_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_unclear_handwritten_prescription),
            ($near_miss->picking_wrong_item_cause_misread_prescription ? ($near_miss->picking_wrong_item_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_misread_prescription),
            ($near_miss->picking_wrong_item_cause_imported_pi_pack ? ($near_miss->picking_wrong_item_cause_imported_pi_pack == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_imported_pi_pack),
            ($near_miss->picking_wrong_item_cause_dispensed_from_picking_label ? ($near_miss->picking_wrong_item_cause_dispensed_from_picking_label == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_dispensed_from_picking_label),
            ($near_miss->picking_wrong_item_cause_unfamiliar_with_item ? ($near_miss->picking_wrong_item_cause_unfamiliar_with_item == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_unfamiliar_with_item),
            ($near_miss->picking_wrong_item_cause_did_not_recheck ? ($near_miss->picking_wrong_item_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_did_not_recheck),
            ($near_miss->picking_wrong_item_cause_other ? ($near_miss->picking_wrong_item_cause_other == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_other),
            ($near_miss->picking_wrong_item_cause_other_field ? ($near_miss->picking_wrong_item_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_item_cause_other_field),
            ($near_miss->picking_wrong_quantity ? ($near_miss->picking_wrong_quantity == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_quantity),
            ($near_miss->picking_wrong_quantity_cause_counting_mistake ? ($near_miss->picking_wrong_quantity_cause_counting_mistake == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_quantity_cause_counting_mistake),
            ($near_miss->picking_wrong_quantity_cause_calculation_error ? ($near_miss->picking_wrong_quantity_cause_calculation_error == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_quantity_cause_calculation_error),
            ($near_miss->picking_wrong_quantity_cause_similar_packaging ? ($near_miss->picking_wrong_quantity_cause_similar_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_quantity_cause_similar_packaging),
            ($near_miss->picking_wrong_quantity_cause_change_in_packaging ? ($near_miss->picking_wrong_quantity_cause_change_in_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_quantity_cause_change_in_packaging),
            ($near_miss->picking_wrong_quantity_cause_did_not_recheck ? ($near_miss->picking_wrong_quantity_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_quantity_cause_did_not_recheck),
            ($near_miss->picking_wrong_quantity_cause_other ? ($near_miss->picking_wrong_quantity_cause_other == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_quantity_cause_other),
            ($near_miss->picking_wrong_quantity_cause_other_field ? ($near_miss->picking_wrong_quantity_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_quantity_cause_other_field),
            ($near_miss->picking_wrong_strength ? ($near_miss->picking_wrong_strength == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength),
            ($near_miss->picking_wrong_strength_drug_prescribed ? ($near_miss->picking_wrong_strength_drug_prescribed == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_drug_prescribed),
            ($near_miss->picking_wrong_strength_drug_labelled ? ($near_miss->picking_wrong_strength_drug_labelled == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_drug_labelled),
            ($near_miss->picking_wrong_strength_cause_similar_name_items ? ($near_miss->picking_wrong_strength_cause_similar_name_items == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_similar_name_items),
            ($near_miss->picking_wrong_strength_cause_similar_packaging ? ($near_miss->picking_wrong_strength_cause_similar_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_similar_packaging),
            ($near_miss->picking_wrong_strength_cause_change_in_packaging ? ($near_miss->picking_wrong_strength_cause_change_in_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_change_in_packaging),
            ($near_miss->picking_wrong_strength_cause_unclear_handwritten_prescription ? ($near_miss->picking_wrong_strength_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_unclear_handwritten_prescription),
            ($near_miss->picking_wrong_strength_cause_misread_prescription ? ($near_miss->picking_wrong_strength_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_misread_prescription),
            ($near_miss->picking_wrong_strength_cause_imported_pi_pack ? ($near_miss->picking_wrong_strength_cause_imported_pi_pack == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_imported_pi_pack),
            ($near_miss->picking_wrong_strength_cause_dispensed_from_picking_label ? ($near_miss->picking_wrong_strength_cause_dispensed_from_picking_label == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_dispensed_from_picking_label),
            ($near_miss->picking_wrong_strength_cause_unfamiliar_with_item ? ($near_miss->picking_wrong_strength_cause_unfamiliar_with_item == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_unfamiliar_with_item),
            ($near_miss->picking_wrong_strength_cause_did_not_recheck ? ($near_miss->picking_wrong_strength_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_did_not_recheck),
            ($near_miss->picking_wrong_strength_cause_other ? ($near_miss->picking_wrong_strength_cause_other == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_other),
            ($near_miss->picking_wrong_strength_cause_other_field ? ($near_miss->picking_wrong_strength_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_strength_cause_other_field),
            ($near_miss->picking_wrong_formulation ? ($near_miss->picking_wrong_formulation == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation),
            ($near_miss->picking_wrong_formulation_drug_prescribed ? ($near_miss->picking_wrong_formulation_drug_prescribed == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_drug_prescribed),
            ($near_miss->picking_wrong_formulation_drug_labelled ? ($near_miss->picking_wrong_formulation_drug_labelled == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_drug_labelled),
            ($near_miss->picking_wrong_formulation_cause_similar_name_items ? ($near_miss->picking_wrong_formulation_cause_similar_name_items == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_similar_name_items),
            ($near_miss->picking_wrong_formulation_cause_similar_packaging ? ($near_miss->picking_wrong_formulation_cause_similar_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_similar_packaging),
            ($near_miss->picking_wrong_formulation_cause_change_in_packaging ? ($near_miss->picking_wrong_formulation_cause_change_in_packaging == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_change_in_packaging),
            ($near_miss->picking_wrong_formulation_cause_unclear_handwritten_prescription ? ($near_miss->picking_wrong_formulation_cause_unclear_handwritten_prescription == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_unclear_handwritten_prescription),
            ($near_miss->picking_wrong_formulation_cause_misread_prescription ? ($near_miss->picking_wrong_formulation_cause_misread_prescription == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_misread_prescription),
            ($near_miss->picking_wrong_formulation_cause_imported_pi_pack ? ($near_miss->picking_wrong_formulation_cause_imported_pi_pack == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_imported_pi_pack),
            ($near_miss->picking_wrong_formulation_cause_dispensed_from_picking_label ? ($near_miss->picking_wrong_formulation_cause_dispensed_from_picking_label == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_dispensed_from_picking_label),
            ($near_miss->picking_wrong_formulation_cause_unfamiliar_with_item ? ($near_miss->picking_wrong_formulation_cause_unfamiliar_with_item == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_unfamiliar_with_item),
            ($near_miss->picking_wrong_formulation_cause_did_not_recheck ? ($near_miss->picking_wrong_formulation_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_did_not_recheck),
            ($near_miss->picking_wrong_formulation_cause_other ? ($near_miss->picking_wrong_formulation_cause_other == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_other),
            ($near_miss->picking_wrong_formulation_cause_other_field ? ($near_miss->picking_wrong_formulation_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->picking_wrong_formulation_cause_other_field),
            ($near_miss->placing_basket_another_patient_label_basket ? ($near_miss->placing_basket_another_patient_label_basket == 1 ? 'yes' : 'no') : $near_miss->placing_basket_another_patient_label_basket),
            ($near_miss->placing_basket_another_patient_cause_weak_adhesive_labels ? ($near_miss->placing_basket_another_patient_cause_weak_adhesive_labels == 1 ? 'yes' : 'no') : $near_miss->placing_basket_another_patient_cause_weak_adhesive_labels),
            ($near_miss->placing_basket_another_patient_cause_area_cluttered_baskets ? ($near_miss->placing_basket_another_patient_cause_area_cluttered_baskets == 1 ? 'yes' : 'no') : $near_miss->placing_basket_another_patient_cause_area_cluttered_baskets),
            ($near_miss->placing_basket_another_patient_cause_basket_was_moved ? ($near_miss->placing_basket_another_patient_cause_basket_was_moved == 1 ? 'yes' : 'no') : $near_miss->placing_basket_another_patient_cause_basket_was_moved),
            ($near_miss->placing_basket_another_patient_cause_labels_stuck_basket ? ($near_miss->placing_basket_another_patient_cause_labels_stuck_basket == 1 ? 'yes' : 'no') : $near_miss->placing_basket_another_patient_cause_labels_stuck_basket),
            ($near_miss->placing_basket_another_patient_cause_other ? ($near_miss->placing_basket_another_patient_cause_other == 1 ? 'yes' : 'no') : $near_miss->placing_basket_another_patient_cause_other),
            ($near_miss->placing_basket_another_patient_cause_other_field ? ($near_miss->placing_basket_another_patient_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->placing_basket_another_patient_cause_other_field),
            ($near_miss->placing_basket_wrong_basket ? ($near_miss->placing_basket_wrong_basket == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_basket),
            ($near_miss->placing_basket_wrong_basket_cause_area_cluttered_baskets ? ($near_miss->placing_basket_wrong_basket_cause_area_cluttered_baskets == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_basket_cause_area_cluttered_baskets),
            ($near_miss->placing_basket_wrong_basket_cause_basket_was_moved ? ($near_miss->placing_basket_wrong_basket_cause_basket_was_moved == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_basket_cause_basket_was_moved),
            ($near_miss->placing_basket_wrong_basket_cause_other ? ($near_miss->placing_basket_wrong_basket_cause_other == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_basket_cause_other),
            ($near_miss->placing_basket_wrong_basket_cause_other_field ? ($near_miss->placing_basket_wrong_basket_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_basket_cause_other_field),
            ($near_miss->placing_basket_missing_item ? ($near_miss->placing_basket_missing_item == 1 ? 'yes' : 'no') : $near_miss->placing_basket_missing_item),
            ($near_miss->placing_basket_missing_item_cause_missing_cd_sticker ? ($near_miss->placing_basket_missing_item_cause_missing_cd_sticker == 1 ? 'yes' : 'no') : $near_miss->placing_basket_missing_item_cause_missing_cd_sticker),
            ($near_miss->placing_basket_missing_item_cause_label_lost ? ($near_miss->placing_basket_missing_item_cause_label_lost == 1 ? 'yes' : 'no') : $near_miss->placing_basket_missing_item_cause_label_lost),
            ($near_miss->placing_basket_missing_item_cause_distracted_item_left_out ? ($near_miss->placing_basket_missing_item_cause_distracted_item_left_out == 1 ? 'yes' : 'no') : $near_miss->placing_basket_missing_item_cause_distracted_item_left_out),
            ($near_miss->placing_basket_missing_item_cause_other ? ($near_miss->placing_basket_missing_item_cause_other == 1 ? 'yes' : 'no') : $near_miss->placing_basket_missing_item_cause_other),
            ($near_miss->placing_basket_missing_item_cause_other_field ? ($near_miss->placing_basket_missing_item_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->placing_basket_missing_item_cause_other_field),
            ($near_miss->placing_basket_label_wrong_item ? ($near_miss->placing_basket_label_wrong_item == 1 ? 'yes' : 'no') : $near_miss->placing_basket_label_wrong_item),
            ($near_miss->placing_basket_wrong_item_cause_weak_adhesive_labels ? ($near_miss->placing_basket_wrong_item_cause_weak_adhesive_labels == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_item_cause_weak_adhesive_labels),
            ($near_miss->placing_basket_wrong_item_cause_similar_name_items ? ($near_miss->placing_basket_wrong_item_cause_similar_name_items == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_item_cause_similar_name_items),
            ($near_miss->placing_basket_wrong_item_cause_similar_packaging ? ($near_miss->placing_basket_wrong_item_cause_similar_packaging == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_item_cause_similar_packaging),
            ($near_miss->placing_basket_wrong_item_cause_change_in_packaging ? ($near_miss->placing_basket_wrong_item_cause_change_in_packaging == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_item_cause_change_in_packaging),
            ($near_miss->placing_basket_wrong_item_cause_did_not_recheck ? ($near_miss->placing_basket_wrong_item_cause_did_not_recheck == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_item_cause_did_not_recheck),
            ($near_miss->placing_basket_wrong_item_cause_other ? ($near_miss->placing_basket_wrong_item_cause_other == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_item_cause_other),
            ($near_miss->placing_basket_wrong_item_cause_other_field ? ($near_miss->placing_basket_wrong_item_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->placing_basket_wrong_item_cause_other_field),
            ($near_miss->bagging_wrong_bag_label ? ($near_miss->bagging_wrong_bag_label == 1 ? 'yes' : 'no') : $near_miss->bagging_wrong_bag_label),
            ($near_miss->bagging_wrong_bag_label_cause_similar_patient_name ? ($near_miss->bagging_wrong_bag_label_cause_similar_patient_name == 1 ? 'yes' : 'no') : $near_miss->bagging_wrong_bag_label_cause_similar_patient_name),
            ($near_miss->bagging_wrong_bag_label_cause_label_reprinted ? ($near_miss->bagging_wrong_bag_label_cause_label_reprinted == 1 ? 'yes' : 'no') : $near_miss->bagging_wrong_bag_label_cause_label_reprinted),
            ($near_miss->bagging_wrong_bag_label_cause_cluttered_bagging_area ? ($near_miss->bagging_wrong_bag_label_cause_cluttered_bagging_area == 1 ? 'yes' : 'no') : $near_miss->bagging_wrong_bag_label_cause_cluttered_bagging_area),
            ($near_miss->bagging_wrong_bag_label_cause_other ? ($near_miss->bagging_wrong_bag_label_cause_other == 1 ? 'yes' : 'no') : $near_miss->bagging_wrong_bag_label_cause_other),
            ($near_miss->bagging_wrong_bag_label_cause_other_field ? ($near_miss->bagging_wrong_bag_label_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->bagging_wrong_bag_label_cause_other_field),
            ($near_miss->bagging_another_patients_med_in_bag ? ($near_miss->bagging_another_patients_med_in_bag == 1 ? 'yes' : 'no') : $near_miss->bagging_another_patients_med_in_bag),
            ($near_miss->bagging_another_patients_med_in_bag_cause_similar_patient_name ? ($near_miss->bagging_another_patients_med_in_bag_cause_similar_patient_name == 1 ? 'yes' : 'no') : $near_miss->bagging_another_patients_med_in_bag_cause_similar_patient_name),
            ($near_miss->bagging_another_patients_med_in_bag_cause_cluttered_bagging_area ? ($near_miss->bagging_another_patients_med_in_bag_cause_cluttered_bagging_area == 1 ? 'yes' : 'no') : $near_miss->bagging_another_patients_med_in_bag_cause_cluttered_bagging_area),
            ($near_miss->bagging_another_patients_med_in_bag_cause_bag_different_patient ? ($near_miss->bagging_another_patients_med_in_bag_cause_bag_different_patient == 1 ? 'yes' : 'no') : $near_miss->bagging_another_patients_med_in_bag_cause_bag_different_patient),
            ($near_miss->bagging_another_patients_med_in_bag_cause_other ? ($near_miss->bagging_another_patients_med_in_bag_cause_other == 1 ? 'yes' : 'no') : $near_miss->bagging_another_patients_med_in_bag_cause_other),
            ($near_miss->bagging_another_patients_med_in_bag_cause_other_field ? ($near_miss->bagging_another_patients_med_in_bag_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->bagging_another_patients_med_in_bag_cause_other_field),
            ($near_miss->bagging_missed_items ? ($near_miss->bagging_missed_items == 1 ? 'yes' : 'no') : $near_miss->bagging_missed_items),
            ($near_miss->bagging_missed_items_cause_cluttered_bagging_area ? ($near_miss->bagging_missed_items_cause_cluttered_bagging_area == 1 ? 'yes' : 'no') : $near_miss->bagging_missed_items_cause_cluttered_bagging_area),
            ($near_miss->bagging_missed_items_cause_distracted_item_left_out ? ($near_miss->bagging_missed_items_cause_distracted_item_left_out == 1 ? 'yes' : 'no') : $near_miss->bagging_missed_items_cause_distracted_item_left_out),
            ($near_miss->bagging_missed_items_cause_missing_cd_sticker ? ($near_miss->bagging_missed_items_cause_missing_cd_sticker == 1 ? 'yes' : 'no') : $near_miss->bagging_missed_items_cause_missing_cd_sticker),
            ($near_miss->bagging_missed_items_cause_other ? ($near_miss->bagging_missed_items_cause_other == 1 ? 'yes' : 'no') : $near_miss->bagging_missed_items_cause_other),
            ($near_miss->bagging_missed_items_cause_other_field ? ($near_miss->bagging_missed_items_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->bagging_missed_items_cause_other_field),
            ($near_miss->preparing_dosette_tray_wrong_day_time ? ($near_miss->preparing_dosette_tray_wrong_day_time == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_wrong_day_time),
            ($near_miss->preparing_dosette_tray_error_patient_mar_chart ? ($near_miss->preparing_dosette_tray_error_patient_mar_chart == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_error_patient_mar_chart),
            ($near_miss->preparing_dosette_tray_extra_quantity_on_tray ? ($near_miss->preparing_dosette_tray_extra_quantity_on_tray == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_extra_quantity_on_tray),
            ($near_miss->preparing_dosette_tray_error_in_description ? ($near_miss->preparing_dosette_tray_error_in_description == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_error_in_description),
            ($near_miss->preparing_dosette_tray_wrong_bag_label ? ($near_miss->preparing_dosette_tray_wrong_bag_label == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_wrong_bag_label),
            ($near_miss->preparing_dosette_tray_external_item_missing ? ($near_miss->preparing_dosette_tray_external_item_missing == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_external_item_missing),
            ($near_miss->preparing_dosette_tray_tray_item_missing ? ($near_miss->preparing_dosette_tray_tray_item_missing == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_tray_item_missing),
            ($near_miss->preparing_dosette_tray_error_on_blister_pack ? ($near_miss->preparing_dosette_tray_error_on_blister_pack == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_error_on_blister_pack),
            ($near_miss->preparing_dosette_tray_blistring_cause_discharge_not_actioned ? ($near_miss->preparing_dosette_tray_blistring_cause_discharge_not_actioned == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_blistring_cause_discharge_not_actioned),
            ($near_miss->preparing_dosette_tray_blistring_cause_change_not_communicated ? ($near_miss->preparing_dosette_tray_blistring_cause_change_not_communicated == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_blistring_cause_change_not_communicated),
            ($near_miss->preparing_dosette_tray_blistring_cause_other ? ($near_miss->preparing_dosette_tray_blistring_cause_other == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_blistring_cause_other),
            ($near_miss->preparing_dosette_tray_blistring_cause_other_field ? ($near_miss->preparing_dosette_tray_blistring_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->preparing_dosette_tray_blistring_cause_other_field),
            ($near_miss->handing_out_to_wrong_patient ? ($near_miss->handing_out_to_wrong_patient == 1 ? 'yes' : 'no') : $near_miss->handing_out_to_wrong_patient),
            ($near_miss->handing_out_to_wrong_patient_cause_similar_patient_name ? ($near_miss->handing_out_to_wrong_patient_cause_similar_patient_name == 1 ? 'yes' : 'no') : $near_miss->handing_out_to_wrong_patient_cause_similar_patient_name),
            ($near_miss->handing_out_to_wrong_patient_cause_did_not_confirm_address ? ($near_miss->handing_out_to_wrong_patient_cause_did_not_confirm_address == 1 ? 'yes' : 'no') : $near_miss->handing_out_to_wrong_patient_cause_did_not_confirm_address),
            ($near_miss->handing_out_to_wrong_patient_cause_other ? ($near_miss->handing_out_to_wrong_patient_cause_other == 1 ? 'yes' : 'no') : $near_miss->handing_out_to_wrong_patient_cause_other),
            ($near_miss->handing_out_to_wrong_patient_cause_other_field ? ($near_miss->handing_out_to_wrong_patient_cause_other_field == 1 ? 'yes' : 'no') : $near_miss->handing_out_to_wrong_patient_cause_other_field),
            ($near_miss->contributing_factor_staff_fewer_staff ? ($near_miss->contributing_factor_staff_fewer_staff == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_staff_fewer_staff),
            ($near_miss->contributing_factor_staff_not_usual_pharmacist ? ($near_miss->contributing_factor_staff_not_usual_pharmacist == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_staff_not_usual_pharmacist),
            ($near_miss->contributing_factor_staff_not_usual_dispense ? ($near_miss->contributing_factor_staff_not_usual_dispense == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_staff_not_usual_dispense),
            ($near_miss->contributing_factor_staff_pharmacist_self_checking ? ($near_miss->contributing_factor_staff_pharmacist_self_checking == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_staff_pharmacist_self_checking),
            ($near_miss->contributing_factor_person_dyslexia ? ($near_miss->contributing_factor_person_dyslexia == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_person_dyslexia),
            ($near_miss->contributing_factor_person_dyscalculia ? ($near_miss->contributing_factor_person_dyscalculia == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_person_dyscalculia),
            ($near_miss->contributing_factor_envirnoment_messy ? ($near_miss->contributing_factor_envirnoment_messy == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_envirnoment_messy),
            ($near_miss->contributing_factor_training_person_in_training ? ($near_miss->contributing_factor_training_person_in_training == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_training_person_in_training),
            ($near_miss->contributing_factor_training_person_not_trained ? ($near_miss->contributing_factor_training_person_not_trained == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_training_person_not_trained),
            ($near_miss->contributing_factor_task_and_workload_high_number_patients ? ($near_miss->contributing_factor_task_and_workload_high_number_patients == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_task_and_workload_high_number_patients),
            ($near_miss->contributing_factor_task_and_workload_busy_otc_trade ? ($near_miss->contributing_factor_task_and_workload_busy_otc_trade == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_task_and_workload_busy_otc_trade),
            ($near_miss->contributing_factor_task_and_workload_backlog_work ? ($near_miss->contributing_factor_task_and_workload_backlog_work == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_task_and_workload_backlog_work),
            ($near_miss->contributing_factor_task_and_workload_quiet_usual ? ($near_miss->contributing_factor_task_and_workload_quiet_usual == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_task_and_workload_quiet_usual),
            ($near_miss->contributing_factor_task_and_workload_telephone_interruption ? ($near_miss->contributing_factor_task_and_workload_telephone_interruption == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_task_and_workload_telephone_interruption),
            ($near_miss->contributing_factor_other ? ($near_miss->contributing_factor_other == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_other),
            ($near_miss->contributing_factor_other_field ? ($near_miss->contributing_factor_other_field == 1 ? 'yes' : 'no') : $near_miss->contributing_factor_other_field),
            $near_miss->created_at,
            $near_miss->what_was_error,
            $near_miss->delete_reason,
            $near_miss->deleted_by,
            $near_miss->deleted_timestamp,
            $near_miss->dispensed_at_hub,
            $near_miss->error
        ];
    }
}
